@startuml
title "Client-X.509 Enrolling a Client"

skinparam BoxPadding 25

entity "Client\nExtension" as client

box "Organization" #LightGray
    entity "Node\nApplication" as app
    entity "Certificate\nDatastore" as crtStore
    entity "Fabric\nCa" as ca
end box

client -> app: ws/register -d\n{crtType : "Client-X.509"\nenId,enSecret}
activate app
app->app: csrInfo = createCSRInfo(enId)
app->client: ws-message sign(csrInfo)
activate client
return signature
app->app: csr = getCSR(csrInfo,signature)
app->ca: enroll(enId,enSecret,csr)
activate ca
return certificate
app->crtStore: put(certificate)
activate crtStore
return OK || 201
return OK || 201
@enduml